taskapp/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from tasks import views
from django.contrib.auth.views import login,logout
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('tasks.urls',namespace='tasks')),
    url(r'^accounts/login/$', login, name='authlogin'),
    url(r'^accounts/logout/$', views.logout_view, name='authlogout'),

]

tasks/urls.py
from django.conf.urls import url
from . import views
from django.contrib.auth.views import login, logout

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^search/$', views.search, name='search'),
    url(r'^task/addsubtasks$', views.addsubtask, name='addsubtask'),
    url(r'^task/(?P<id>.+)$', views.taskview, name='taskview'),
    url(r'^tasklist/(?P<id>.+)$', views.tasklistview, name='tasklistview'),

]

tasks/models.py
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError


class UserManager(models.Manager):
    def get(self, user_id):
        customuser=UserModel.objects.get(user=user_id)
        if customuser.user_role == 'employee':
            user_tasklists=[]
            tasklists=TasklistUserModel.objects.filter(user_id=user_id)
            for tasklist in tasklists:
                user_tasklists += TaskList.objects.filter(id=tasklist.id)
            return user_tasklists
        else:
            return TaskList.objects.all()

class Project(models.Model):
    description = models.CharField(max_length=300, null=True, blank=True)
    status = models.CharField(max_length=20)
    start_date = models.DateField(null=True, blank=True)
    end_date = models.DateField(null=True, blank=True)
    is_followed = models.BooleanField(default=False)

    def enddate_check(self):
        if self.end_date <= self.start_date:
            raise ValidationError(
                ('%(end_date) can not be less than %(start_date)'),
                params={'end_date': self.end_date, 'start_date': self.start_date},
            )
    def __str__(self):
        return str(self.id)


class MileStone(models.Model):
    description = models.CharField(max_length=300, null=True, blank=True)
    project_id = models.ForeignKey(Project, null=True, blank=True)
    status = models.BooleanField(default='open')

    def __str__(self):
        return str(self.id)


class TaskList(models.Model):
    name=models.CharField(max_length=30)
    description = models.CharField(max_length=300, null=True, blank=True)
    milestone_id = models.ForeignKey(MileStone, null=True, blank=True)
    notes = models.CharField(max_length=300, null=True, blank=True)
    status = models.CharField(max_length=10,default='open',choices=(('open','open'),('closed','closed')))
    objects=models.Manager()
    user_objects=UserManager()

    def __str__(self):
        return str(self.id)


class TasksModel(models.Model):
    name = models.CharField(max_length=20)
    completion_status = models.FloatField(default=0)
    description = models.TextField(max_length=300, null=True)
    start_date = models.DateField(null=True, blank=True)
    end_date = models.DateField(null=True, blank=True)
    tasklist_id = models.ForeignKey(TaskList, null=True, blank=True)
    root_id = models.IntegerField(null=True, blank=True)
    parent_id = models.IntegerField(null=True, blank=True)

    def __str__(self):
        return self.name.title()


class UserModel(models.Model):
    user=models.ForeignKey(User)
    user_rate = models.FloatField(default=0)
    user_role=models.CharField(max_length=15,choices=(('employee','employee'),('manager','manager'),('admin','admin')),default='employee')
    contact_number = models.CharField(max_length=10,default='')
    project_id = models.ForeignKey(Project, null=True,blank=True)

    def __str__(self):
        return self.user.username.title()


class CommentsModel(models.Model):
    task_id = models.ForeignKey(TasksModel)
    comment = models.CharField(max_length=300)

    def __str__(self):
        return self.comment.title()

class TasklistUserModel(models.Model):
    tasklist_id=models.ForeignKey(TaskList)
    user_id=models.ForeignKey(User)

tasks/forms.py
from tasks.models import TasksModel, TaskList, UserModel,CommentsModel
from django import forms


class TaskForm(forms.ModelForm):
    name = forms.CharField(widget=forms.TextInput(
        attrs={'class': 'form-control'}
    ))
    completion_status = forms.FloatField(widget=forms.NumberInput(
        attrs={'class': 'form-control', 'value': 0}
    ))
    description = forms.CharField(max_length=300, widget=forms.Textarea(
        attrs={'class': 'form-control'}
    ))

    def __init__(self, *args, **kwargs):
        super(TaskForm, self).__init__(*args, **kwargs)

        for key, field in self.fields.iteritems():
            if key == 'description':
                self.fields[key].required = False
    class Meta:
        model = TasksModel
        fields = ['name', 'completion_status', 'description']


class TasklistForm(forms.ModelForm):
    name = forms.CharField(widget=forms.TextInput(
        attrs={'class': 'form-control'}
    ))
    description = forms.CharField(widget=forms.Textarea(
        attrs={'class': 'form-control'}
    ))
    notes = forms.CharField(widget=forms.Textarea(
        attrs={'class': 'form-control'}
    ))
    status = forms.CharField(widget=forms.Textarea(
        attrs={'class': 'form-control'}
    ))

    def __init__(self, *args, **kwargs):
        super(TasklistForm, self).__init__(*args, **kwargs)

        for key, field in self.fields.iteritems():
            if key != 'name':
                self.fields[key].required = False

    class Meta:
        model = TaskList
        fields = ['name','description', 'notes', 'status']

class CommentForm(forms.ModelForm):
    comment=forms.CharField(widget=forms.TextInput(
        attrs={'class':'form-control','placeholder':'Write Your Comment Here'}
    ),label='')
    class Meta:
        model=CommentsModel
        fields=['comment']


class Subtaskform(TaskForm):
    pass

tasks/views.py
from django.shortcuts import render, redirect, HttpResponse
from tasks.models import *
from tasks.forms import TaskForm, TasklistForm, CommentForm, Subtaskform
from appmethods import create_task, create_tasklist, modelsearch, add_users
from django.contrib import auth
from django.contrib.auth.decorators import login_required


def logout_view(request):
    auth.logout(request)
    return redirect('tasks:index')


@login_required
def index(request):
    if request.method == 'GET':
        taskform = TaskForm()
        tasklistform = TasklistForm()
        all_tasks = TasksModel.objects.all().filter(parent_id=None)
        tasklists = TaskList.user_objects.get(request.user.id)
        orphan_tasks = TasksModel.objects.filter(tasklist_id=None)
        user_role= UserModel.objects.get(user=request.user.id).user_role
        return render(request, 'tasks/index.html',
                      context={'all_tasks': all_tasks, 'tasklists': tasklists, 'taskform': taskform,
                               'tasklistform': tasklistform, 'orphan_tasks': orphan_tasks,'role':user_role})
    if request.method == 'POST':
        formname = request.POST['formname']
        if formname == 'task':
            exitcode = create_task(request.POST)
            if exitcode == 0:
                return redirect('tasks:index')
            elif exitcode == 255:
                taskform = TaskForm(request.POST)
                return redirect('tasks:index')
        elif formname == 'tasklist':
            exitcode = create_tasklist(request.POST)
            if exitcode == 0:
                return redirect('tasks:index')
            elif exitcode == 255:
                tasklistform = TasklistForm(request.POST)
                return redirect('tasks:index')


@login_required
def taskview(request, id):
    if request.method == 'GET':
        task = TasksModel.objects.get(id=id)
        comments = CommentsModel.objects.filter(task_id=id)
        commentform = CommentForm()
        tasklists = TaskList.objects.all()
        taskform = TaskForm(instance=task)
        subtaskform = Subtaskform()
        user_role= UserModel.objects.get(user=request.user.id).user_role
        is_allowed = TasklistUserModel.objects.filter(tasklist_id=task.tasklist_id, user_id=request.user)
        sub_tasks = TasksModel.objects.filter(parent_id=id)
        if task.parent_id:
            parent = TasksModel.objects.get(id=task.parent_id)
        else:
            parent = None
        if len(is_allowed) or user_role != 'employee':
            return render(request, 'tasks/task.html',
                      context={'task': task, 'comments': comments, 'commentform': commentform, 'taskform': taskform,
                               'tasklists': tasklists, 'subtaskform': subtaskform, 'role': user_role,
                               'subtasks': sub_tasks, 'parent': parent})
        else:
            return HttpResponse("You dont have permissions to view this page.")

    if request.method == 'POST':
        task = TasksModel.objects.get(id=id)
        try:
            formname = request.POST['formname']
        except:
            formname = None
        if formname == 'task':
            exitcode = create_task(request.POST, method='edit', instance=task)
            if exitcode == 0:
                return redirect('tasks:taskview', id)
            elif exitcode == 255:
                taskform = TaskForm(request.POST)
                return HttpResponse(taskform.errors)
        elif formname is None:
            commentform = CommentForm(request.POST)
            if commentform.is_valid():
                comment_text = commentform.cleaned_data['comment']
                comment = CommentsModel(task_id=task, comment=comment_text)
                comment.save()
            return redirect('tasks:taskview', id)


@login_required
def tasklistview(request, id):
    if request.method == 'GET':
        if id == '0':
            tasks = TasksModel.objects.filter(tasklist_id=None)
            return render(request, 'tasks/orphan_tasks.html', context={'tasks': tasks})
        else:
            tasklist = TaskList.objects.get(id=id)
            tasklistform = TasklistForm(instance=tasklist)
            tasks = TasksModel.objects.filter(tasklist_id=id)
            user_role = UserModel.objects.get(user=request.user.id).user_role
            is_allowed=TasklistUserModel.objects.filter(tasklist_id=tasklist,user_id=request.user)
            usersshared = [UserModel.objects.get(user=i.user_id) for i in
                           TasklistUserModel.objects.filter(tasklist_id=tasklist)]
            usersshared = list(set(usersshared))
            users = list(set(UserModel.objects.all()))
            for user in usersshared:
                if user in users:
                    users.remove(user)

            if len(is_allowed) or user_role != 'employee':
                return render(request, 'tasks/tasklist.html',
                              context={'tasklist': tasklist, 'tasklistform': tasklistform, 'tasks': tasks,'users':users,
                                       'role': user_role, 'usersshared': usersshared,})
            else:
                return HttpResponse("You dont have permissions to view this page.")
    if request.method == 'POST':
        tasklist = TaskList.objects.get(id=id)
        try:
            formname = request.POST['formname']
        except:
            formname = None
        if formname == 'tasklist':
            exitcode = create_tasklist(request.POST, method='edit', instance=tasklist)
            if exitcode == 0:
                return redirect('tasks:tasklistview', id)
            elif exitcode == 255:
                tasklistform = TasklistForm(request.POST)
                return HttpResponse(tasklistform.errors)
        elif formname == 'addusers':
            exitcode=add_users(request.POST,id)
            return redirect('tasks:tasklistview', id)


@login_required
def search(request):
    query = None
    if 'query' in request.POST:
        query = request.POST['query']
    if query is not None and len(query.strip()) != 0:
        context = modelsearch(query)
        return render(request, 'tasks/search.html', context=context)
    else:
        return redirect('tasks:index')


@login_required
def subtasksretrive(request, id):
    if request.method == 'GET':
        task = TasksModel.objects.get(id=id)
        return render(request, 'tasks/subtasks.html', context={})
    if request.method == 'POST':
        try:
            subtask1 = TasksModel.objects.filter(parent_id=id)
            return render(request, 'tasks/subtasks.html', context={"subtasks": subtask1})
        except:
            return render(request, 'tasks/dialog.html', context={"msg": "No SubTasks exist"})

    return


@login_required
def addsubtask(request):
    if request.method == 'POST':
        tasklist_id = request.POST['tasklist_id']
        taskform = Subtaskform()
        parentid = request.POST['parentid']
        exitcode = create_task(request.POST, 'subtask')
        return redirect('tasks:taskview', parentid)

tasks/templates/tasks/adduserform_modal.html
<div class="modal fade" id="AddUserModal" tabindex="-1" role="dialog" aria-labelledby="AddUserLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                        aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="AddUserLabel">Add Task</h4>
            </div>
            <div class="modal-body">
                <form method="post" class="form-horizontal adduserform">
                    {% csrf_token %}
                    <label for="adduser">Add User:</label>
                    <select class="form-control" id="adduser" name="adduser" multiple>
                        {% for user in users %}
                            <option value="{{ user.user.id }}">{{ user.user.username }}</option>
                        {% endfor %}
                    </select>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary" id="addusers">Add  Users</button>
            </div>
        </div>
    </div>
</div>

<script>
    $('#addusersmodal').click(function () {
        $('form.adduserform').append('<input type="hidden" name="tasklist_id" value="{{ tasklist.id }}">');
        $('form.adduserform').append('<input type="hidden" name="formname" value="addusers">');
    });
    $('#addusers').click(function () {
        $('form.adduserform')[0].submit();
    });
</script>

tasks/templates/tasks/index.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block content %}
  {% if tasklistform.errors %}
    <p class="error">Sorry, that's not a valid data in Form</p>
  {% endif %}
  {% if taskform.errors %}
    <p class="error">Sorry, that's not a valid data in Form</p>
  {% endif %}

    <div>
        <button type="button" class="btn btn-primary" id="addtasklist" data-toggle="modal" data-target="#AddTaskListModal" >Add TaskList</button>
        <button type="button" class="btn btn-primary" id="addtask" data-toggle="modal" data-target="#AddTaskModal" >Add Task</button>
    </div>
    <div class='col-md-12' style="margin-top: 10px;">
        <a style="
    color: #4617f5;
    font-size: 16px;
    font-family: monospace;
" href="{% url 'tasks:tasklistview' 0 %}">Orphaned Tasks</a>
    </div>
    <table>
        <tbody>
        {% for orphan_task in orphan_tasks %}
            <tr>
                <td>
                    <div style="margin-left: 40px;" class="col-md-6 col-md-offset-1">
                        <a style="
    min-width: 1000px;
    margin-left: 40px;
    max-width: 10000px;
" href="{% url 'tasks:taskview' orphan_task.id %}">{{ orphan_task.name }}</a></div>
                </td>
            </tr>

        {% endfor %}

        </tbody>
    </table>

    <br>

    {% for tasklist in tasklists %}
        <div class='col-md-12'>
            <a style="
    color: #a02ad8;
    font-size: 16px;
    font-family: monospace;
" href="{% url 'tasks:tasklistview' tasklist.id %}">{{ tasklist.name }}</a>
        </div>

        {% for task in all_tasks %}
            <table>
            <tbody>

            {% if task.tasklist_id == tasklist %}
                <tr>
                    <td>
                        <div class="col-md-20 col-md--1"
                             style="font-size: 16px;font-family: monospace;margin-left: 95px">
                            <a href="{% url 'tasks:taskview' task.id %}">{{ task.name }}</a></div>
                    </td>
                </tr>
            {% endif %}


        {% endfor %}
    </tbody>
    </table>
        <br>
    {%endfor%}


    {% include 'tasks/taskform_modal.html' %}
    {% include 'tasks/tasklistform_modal.html' %}


{% endblock%}

tasks/templates/tasks/orphan_tasks.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block content %}
    <div class="col-sm-11">
        <h3>Orphan Tasks</h3>
    </div>
    <table class="table table-hover">
        <thead>
        <tr>
            <td>Taskname</td>
            <td>Progress</td>
            <td>Start Date</td>
            <td>End Date</td>
        </tr>
        </thead>
        <tbody>
        {% for task in tasks %}
            <tr>
                <td><a href="{% url 'tasks:taskview' task.id %}">{{ task.name }}</a></td>
                <td>
                    <div class="progress">
                        <div class="progress-bar progress-bar-success progress-bar-striped" role="progressbar"
                             aria-valuenow="{{ task.completion_status }}" aria-valuemin="0" aria-valuemax="100"
                             style="width: {{ task.completion_status }}%">
                            <span class="sr-only">{{ task.completion_status }}% Complete (success)</span>
                        </div>
                    </div>
                </td>
                <td>{{ task.start_date }}</td>
                <td>{{ task.end_date }}</td>
            </tr>
        {% endfor %}
        </tbody>
        {% for task in tasks %}

        {% endfor %}
    </table>
    {% include 'tasks/tasklistform_modal.html' %}
{% endblock %}

tasks/templates/tasks/search.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block content %}
<h3>Search Results for '{{ query }}'</h3>
    {% if tasklists_number != 0 %}
        <div>
            <h4>Tasklists</h4>
            <ul>
                {% for tasklist in tasklists %}
                    <li>{{ tasklist.name }}</li>
                {% endfor %}
                {% for tasklist in tasklists_description %}
                    <li>{{ tasklist.name }}
                        <div class="well">{{ tasklist.description }}</div>
                    </li>
                {% endfor %}
                {% for tasklist in tasklists_notes %}
                    <li>{{ tasklist.name }}
                        <div class="well">{{ tasklist.notes }}</div>
                    </li>
                {% endfor %}
            </ul>
        </div>
    {% endif %}
    {% if tasks_number != 0 %}
        <div>
            <h4>Tasks:</h4>
            <ul>
                {% for task in tasks %}
                    <li><a href="{% url 'tasks:taskview' task.id %}">{{task}}</a></li>
                {% endfor %}
                {% for task in tasks_description %}
                    <li><a href="{% url 'tasks:taskview' task.id %}">{{task}}</a>
                        <div class="well">{{ task.description }}</div>
                    </li>
                {% endfor %}
                {% for task in tasks_comments %}
                    <li><a href="{% url 'tasks:taskview' task.id %}">{{task}}</a>
                        {% for comment in comments %}
                            <ul>
                                {% if comment.task_id.id == task.id %}
                                    <li>{{ comment.comment }}</li>
                                {% endif %}
                            </ul>
                        {% endfor %}
                    </li>
                {% endfor %}
            </ul>
        </div>
    {% endif %}
    {% if tasklists_number == 0 and tasks_number == 0 %}
        <p>No Results matching Your Query</p>
    {% endif %}

{% endblock %}

tasks/templates/tasks/subtaskform_modal.html
<div class="modal fade" id="AddSubTaskModal" tabindex="-1" role="dialog" aria-labelledby="AddSubTaskLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                        aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="AddSubTaskLabel">Add Sub Task</h4>
            </div>
            <div class="modal-body">
                <form action="{% url 'tasks:addsubtask' %}" method="post" class="form-horizontal subtaskform">
                    {% csrf_token %}
                    {{ subtaskform }}
                    <label for="startdate">Start Date:</label>
                    <input type="date" class="form-control" id="startdate" placeholder="Start Date" name="start_date"
                           value="{{ task.start_date|date:"Y-m-d" }}">
                    <label for="enddate">End Date:</label>
                    <input type="date" class="form-control" id="enddate" placeholder="End Date" name="end_date"
                           value="{{ task.end_date|date:"Y-m-d" }}">
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary" id="createsubtask">Create Sub Task</button>
            </div>
        </div>
    </div>
</div>

<script>
    $('#add_subtasks').click(function () {
        $('form.subtaskform').append('<input type="hidden" name="parentid" value="{{ task.id }}">');
        $('form.subtaskform').append('<input type="hidden" name="tasklist_id" value="{{ task.tasklist_id.id }}">');
    });
    $('#createsubtask').click(function () {
        $('form.subtaskform')[0].submit();
    });
</script>

tasks/templates/tasks/subtasks.html
{%  extends 'base.html' %}
{%  load staticfiles %}
{% block %}
    {% if msg %}
        {{ msg }}
    {% endif %}
{% for subtask in subtasks %}
    <div>
        {{ subtask.taskname }}
    </div>
{% endfor %}
{% endblock %}

tasks/templates/tasks/task.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block content %}
    {% if task.parent_id == None %}
        <h3>TASK </h3>
    {% else %}
        <h3>SUB TASK </h3>
    {% endif %}
    <div class="col-sm-11">
        <h4 style="margin-left:-15px;"> {{ task.name }}</h4>
    </div>

    <span class="input-group-btn">
        <button type="button" class="btn btn-default glyphicon glyphicon-edit pull-left" id="addtask"
                data-toggle="modal" data-target="#AddTaskModal" style="white-space: nowrap;
    text-align: center;
    padding-top: 2px;
    padding-bottom: 2px;
    margin: 0px 7px;
    border-radius: 20px;"> Edit</button>
    </span>
    <br />
    {% if task.parent_id == None %}
        <div id="add_subtasks" data-toggle="modal" data-target="#AddSubTaskModal" style="float:right;
    color:rgb(255,255,255);
    background-color: rgba(32, 141, 244, 0.8);
    text-overflow: ellipsis;
    white-space: nowrap;
    text-align: center;
    padding-top: 2px;
    padding-bottom: 2px;
    margin: 0px 7px;
    border-radius: 20px;
    -webkit-border-radius: 20px;
    padding: 0px 9px;cursor:pointer;">Add Sub Tasks
        </div>
        <div id="subtasks" style="float:right;
    color:rgb(255,255,255);
    background-color: rgba(32, 141, 244, 0.8);
    text-overflow: ellipsis;
    white-space: nowrap;
    text-align: center;
    padding-top: 2px;
    padding-bottom: 2px;
    margin: 0px 7px;
    border-radius: 20px;
    -webkit-border-radius: 20px;
    padding: 0px 9px;cursor:pointer;"> View Sub Tasks
        </div>
    {% endif %}

    <br/>
    <br/>
    <div class="well" style="display: None" id="subtasksdiv">
        <strong>SubTasks:</strong>
        <ul>
            {% for subtask in subtasks %}
                <li><a href="{% url 'tasks:taskview' subtask.id %}">{{ subtask.name }}</a></li>
            {% endfor %}
        </ul>
    </div>
    <p><b>Tasklist:</b> <a href="{% url 'tasks:tasklistview' task.tasklist_id %}"> <strong
            style="color:#286090">{{ task.tasklist_id.name }}</strong></a></p>
    {% if task.parent_id != None %}
        <p><b>ParentTask:</b> <a href="{% url 'tasks:taskview' task.parent_id %}"> <strong
                style="color:#286090">{{ parent.name }}</strong></a></p>
    {% endif %}

    <b>Progress:</b>
    <div class="progress">
      <div class="progress-bar progress-bar-success progress-bar-striped" role="progressbar" aria-valuenow="{{ task.completion_status }}" aria-valuemin="0" aria-valuemax="100" style="width: {{ task.completion_status }}%">
        <span class="sr-only">{{ task.completion_status }}% Complete (success)</span>
      </div>
    </div>
    <div><b>Description:</b>
        <div class="well">{{ task.description }}</div>
    </div>
    <p><b>Start Date:</b>{{ task.start_date }}</p>
    <p><b>End Date:</b>{{ task.end_date }}</p>
    <div>
        <b>Comments:</b>
        <div class="well">
            <form method="POST">
                {% csrf_token %}
                <div class="col-sm-11">
                    {{ commentform }}
                </div>
                <span class="input-group-btn">
                    <button type="submit" class="btn btn-default glyphicon glyphicon-comment pull-left"></button>
                </span>
            </form>
            <ul>
                {% for comment in comments %}
                    <li>{{ comment }}</li>
                {% endfor %}
            </ul>
        </div>
    </div>
    {% include 'tasks/taskform_modal.html' %}
    {% include 'tasks/subtaskform_modal.html' %}
{% endblock %}

{% block scripts %}
    <script>
        $('#subtasks').click(function () {
            $('div#subtasksdiv').toggle();
        });
        function csrfSafeMethod(method) {
            // these HTTP methods do not require CSRF protection
            return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
        }
        function getCookie(name) {
            var cookieValue = null;
            if (document.cookie && document.cookie !== '') {
                var cookies = document.cookie.split(';');
                for (var i = 0; i < cookies.length; i++) {
                    var cookie = jQuery.trim(cookies[i]);
                    // Does this cookie string begin with the name we want?
                    if (cookie.substring(0, name.length + 1) === (name + '=')) {
                        cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                        break;
                    }
                }
            }
            return cookieValue;

        }
        var csrftoken = getCookie('csrftoken');
        {#        jQuery('#createsubtask').click(function(){#}
        {#            console.log({{ task }});#}
        {#            url="{% url 'tasks:addsubtask' %}";#}
        {##}
        {#            ddata="X-CSRFToken="+csrftoken+"&task_id={{ task }}&tasklist_id={{ task.tasklist_id }}";#}
        {#           jQuery.ajax({#}
        {#              dataType :"html",#}
        {#               url:url,#}
        {#               data:ddata,#}
        {#               type:"POST",#}
        {##}
        {#               beforeSend: function (xhr, settings) {#}
        {#                   if (!csrfSafeMethod(settings.type) && !this.crossDomain) {#}
        {#                       xhr.setRequestHeader("X-CSRFToken", csrftoken);#}
        {#                   }#}
        {#                   $('#createsubtask').click(function(){#}
        {#                             $('form.subtaskform')[0].submit();#}
        {#                   });#}
        {#               },#}
        {##}
        {##}
        {##}
        {#               success: function (data) {#}
        {##}
        {#                    console.log('Success');#}
        {#               }#}
        {##}
        {#           });#}
        {#        });#}
    </script>
{% endblock %}

tasks/templates/tasks/taskform_modal.html
<div class="modal fade" id="AddTaskModal" tabindex="-1" role="dialog" aria-labelledby="AddTaskLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="AddTaskLabel">Add Task</h4>
      </div>
      <div class="modal-body">
        <form action="" method="post" class="form-horizontal taskform">
            {% csrf_token %}
            {{ taskform }}
            <label for="startdate">Start Date:</label>
            <input type="date" class="form-control" id="startdate" placeholder="Start Date"  name="start_date" value="{{task.start_date|date:"Y-m-d" }}">
            <label for="enddate">End Date:</label>
            <input type="date" class="form-control" id="enddate" placeholder="End Date" name="end_date" value="{{ task.end_date|date:"Y-m-d" }}">
            <label for="Tasklist">Tasklist:</label>
            <select class="form-control" id="Tasklist" name="tasklist_id" >
                <option disabled selected value=" "> -- select an option -- </option>
                {% for tasklist in tasklists %}
                    <option value="{{ tasklist.id }}">{{tasklist.name}}</option>
                {% endfor %}
            </select>
        </form>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary" id="createtask">Create Task</button>
      </div>
    </div>
  </div>
</div>

{% if task.id %}
    <script>
        jQuery('#Tasklist').find('[value={{task.tasklist_id}}]').attr("selected", true);
    </script>
{% endif %}
{% if  task.start_date == None %}
    <script>
        Date.prototype.toDateInputValue = (function () {
            var local = new Date(this);
            local.setMinutes(this.getMinutes() - this.getTimezoneOffset());
            return local.toJSON().slice(0, 10);
        });
        $('#startdate').val(new Date().toDateInputValue());
        $('#enddate').val(new Date().toDateInputValue());
        /*var date=new Date();
         datestring=date.getFullYear()+'-'+date.getMonth()+'-'+date.getDate();
         jQuery('#startdate').attr('value',date);
         jQuery('#enddate').attr('value',date);
         */
    </script>

{% endif %}

<script>
    $('#addtask').click(function(){
        $('form.taskform').append('<input type="hidden" name="formname" value="task">');
    });
    $('#createtask').click(function(){
        $('form.taskform')[0].submit();
    });
</script>